# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Kany Garcia
description: "My portfolio focuses on interesting projects I have recently undertaken, with a strong emphasis on business impact. To find more, please visit my Github & LinkedIn pages by using the links below."
</p>
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: <span style="color:#48C9B0"> Data & Analytics Portfolio </span> 
</p>

location: "Valencia, Spain"
tableau: "https://public.tableau.com/app/profile/kanygarcia/#"  # Add your tableau handle
# resume_url: /docs/resume 2022.docx
avatar_image: /img/my_profile_picture.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/kanygarcia/#" # Add your linkedln handle
github: "https://github.com/kanygarcia/#"  # Add your github handle
tableau: "https://public.tableau.com/app/profile/kanygarcia/#"  # Add your tableau handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

